### ISSUE TITLE
CODE REVIEW 01

### ISSUE THREAD

**Issue by oki-rakhim** [suryakka/parking-lot#2]
CODE REVIEW

overall is nice. good job.
1. good readme file
2. unit testing

but there's one code duplication issue:

you have a function to check whether any available parking slot, you use inside `park` function.
the duplication code is there when you still do the search thru `parkingslot` array again for null value just to return the index value.

instead of returning boolean, to avoid unnecessary duplicate code, you can return the index as well.

something like object with the stub similar like this:
{
   isAvailable: true,
   slotNumber: 3
}

or 

{
   isAvailable: false,
   slotNumber: null
}

############################

AREA of IMPROVEMENT 

1. what if, not just a car, but it also truck who can park there which it requires two consecutive slots. And a motobike. Each slot can park max 2 bikes.
2. what if, the charges is changing. like charges for regular customer or special event. Or something in the future you don't know yet. What's your strategy?
3. instead of always searching for available slot when a car wants to park, why don't you make a function that always hold the availability status and its data.

**Comment by suryakka** [comment]
@oki-rakhim  Thank you very much for participating and reviewing my code. Based on the suggestions that have been given. I've made improvements to the branch https://github.com/suryakka/parking-lot/tree/code-review-1
Please check and give me your honest feedback 

Thank you :)

**Comment by suryakka** [comment]
############################
Q : what if, not just a car, but it also truck who can park there which it requires two consecutive slots. And a motobike. Each slot can park max 2 bikes.
A: maybe i will make an abstract class named vehicle that have fields vehicleType and vehicleCapacit to provide an different vehicle type. then make adjustment in service and add some conditional to check availabiltity in parking lot slot that can accommodate vehicles that have various capacities in the parking lot. after that, maybe i can adjust park command with adding new parameter vehicle type like : park car KA-1234-HH, park motorcycle KA-4321-HH

Q: what if, the charges is changing. like charges for regular customer or special event. Or something in the future you don't know yet. What's your strategy?
A: make new command to setting the park charge, example : charge 30 > setting : Charge applicable is $30 for first 2 hours and $30 for every additional hour. then if owner want to change discount like aplicable charge is for first 3/(n) hours or for some duration will take less charge or something. then i will make new configuration charge command hehe

**Comment by oki-rakhim** [comment]
A. you dont need vehicleType actually, the class's name will tell the different.

B. use Strategy Pattern. Hint: Create interface class , name ICharge. Implement it in different classes.
